name: branch-validation
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  my-branch-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "Sleeping for 35 seconds"
          sleep 35
          echo "Hello"