name: main-process
on:
  pull_request:
    types:
      - closed

concurrency: main-process
jobs:
  main-process:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get access token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 281001
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: main

#      - name: Update file
#        run: echo "`date`" >> hello.txt

      - name: Add and commit files
        id: stepAddAndCommit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'My automatic commit'
          push: false

      - name: Push to main
        if: ${{ steps.stepAddAndCommit.outputs.committed == 'true' }}
        run: bash ./push-protect.sh

      - name: Nothing to commit
        if: ${{ steps.stepAddAndCommit.outputs.committed != 'true' }}
        run: echo "Nothing to commit"
