name: secrets-sync
on: [workflow_dispatch]
jobs:
  secrets-sync:
    runs-on: ubuntu-latest
    env:
      MY_SYNC_SECRET: ${{ secrets.MY_SYNC_SECRET }}
      OTHER_SYNC_SECRET: ${{ secrets.OTHER_SYNC_SECRET }}
    steps:
      - name: Get repos from var
        run: |
          echo "TARGET_REPOS_ENV<<EOF" >> $GITHUB_ENV
          echo "${{ vars.TARGET_RESPOSITORIES }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
    
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.7.1
        with:
          repositories: |
            ${{ env.TARGET_REPOS_ENV }}
          repositories_list_regex: false
          secrets: |
            ^MY_SYNC_SECRET$
            ^OTHER_SYNC_SECRET$
          github_token: ${{ secrets.MY_TOKEN }}  
          
