name: secrets-sync
on: [workflow_dispatch]
jobs:
  secrets-sync
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: google/secret-sync-action@1.7.1
        repositories: |
          indra-rosadi-rally/irosadi-test-repo
        repositories_list_regex: false
        secrets: |
          ^MY_REPO_PAT$
          ^PRIVATE_KEY$
        github_token: ${{ secrets.MY_TOKEN }}  
          
