name: secrets-sync
on: [workflow_dispatch]
jobs:
  secrets-sync:
    runs-on: ubuntu-latest
    env:
      MY_SYNC_SECRET: ${{ secrets.MY_SYNC_SECRET }}
      OTHER_SYNC_SECRET: ${{ secrets.OTHER_SYNC_SECRET }}
    steps:
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.7.1
        with:
          repositories: ${{ vars.TARGET_RESPOSITORIES }}
          repositories_list_regex: false
          secrets: |
            ^MY_SYNC_SECRET$
            ^OTHER_SYNC_SECRET$
          github_token: ${{ secrets.MY_TOKEN }}  
          
