name: trigger-update
on:
    push:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo update
        run: |
          curl -X POST https://api.github.com/repos/indra-rosadi-rally/irosadi-test-repo/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u indra-rosadi-rally:${{ secrets.MY_REPO_PAT }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "arst" }}

